macOS: Try switching to Qbs from Qt Creator
Hoping to avoid that error, which we're seeing in CI for the macOS builds using Qbs installed
through Homebrew:

ERROR: Failed to start process launcher at '/opt/homebrew/libexec/qbs/qbs_processlauncher': Child
process set up failed: execve: No such file or directory