Added support for exporting to RPTools MapTool (#2926)
This new RpMap plugin adds support for exporting to the RPTools MapTool RpMap format.

Added `src/karchive` based on KArchive commit 0d55829a2ce093e83c68ac0d1cbef8b6a1814332.

The plugin is disabled when compiling with MSVC due to an unresolved linker error:

karchive.lib(karchive.cpp.obj) : error LNK2019: unresolved external symbol __imp_GetUserNameW referenced in function "class QString __cdecl getCurrentUserName(void)" (?getCurrentUserName@@YA?AVQString@@XZ)
C:\projects\tiled\release\rpmap.bf8dc609\rpmap.dll : fatal error LNK1120: 1 unresolved externals

Closes #2922

Co-authored-by: Thorbjørn Lindeijer <bjorn@lindeijer.nl>