Fixed compile error with MSVC 2013
This strange error popped up in MSVC 2013:

src\tiled\terrainbrush.cpp(379) : error C2327: 'Tiled::Internal::TerrainBrush::mMirrorDiagonally' : is not a type name, static, or enumerator
src\tiled\terrainbrush.cpp(379) : error C2065: 'mMirrorDiagonally' : undeclared identifier

This didn't make any sense, and I fixed it by using a bit less fancy C++
features (not sure what part broke it, though).