Fixed compile error with GCC 5.4
Not sure if this was an actual code error, but GCC 5.4 is giving the
following error:

    error: use of ‘entry’ before deduction of ‘auto’

Local GCC 9.2 and Clang 7.0 are not complaining. Intuitively I would
expect that the two "entry" variables live in different scopes.