macOS: Removed the special code for enabling full screen
Not sure this code is still needed on current macOS versions. When
compiling against Qt 5.12 it appears to cause the following errors:

ERROR: Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in macsupport.mm.o
  "_objc_msgSend", referenced from:
      MacSupport::isLion() in macsupport.mm.o
      MacSupport::addFullscreen(Tiled::MainWindow*) in macsupport.mm.o