Added a semicolon to the tiled.desktop file
As reported by 'desktop-file-validate' on openSUSE Build Service:

error: value "application/x-tiled-tmx" for string list key "MimeType" in
group "Desktop Entry" does not have a semicolon (';') as trailing
character