Fixed compile on macOS
The constexpr std::array worked almost everywhere, except for the Clang
build on macOS, where I got the following error:

src/tiled/objectreferenceitem.cpp:70:45: error: constexpr variable cannot have non-literal type 'const std::array<QPointF, 4>'
    static constexpr std::array<QPointF, 4> arrowHead = {
                                            ^

This might be related to QPointF, since it did compile against Qt 6,
also with Clang on macOS.