Fixed compile with MSVC 2013
There's something about the Q_ASSERT macro in Qt 5.9.5 that causes the
following compiler error in this context:

  createpolygonobjecttool.cpp(483) : error C2059: syntax error : '}'
  createpolygonobjecttool.cpp(483) : error C2065: 'handle' : undeclared identifier
  createpolygonobjecttool.cpp(483) : error C2227: left of '->mapObject' must point to class/struct/union/generic type
          type is 'unknown-type'
  createpolygonobjecttool.cpp(483) : fatal error C1903: unable to recover from previous error(s); stopping compilation

Since we don't really need this assert, I've chosen just to remove it.