Fixed compile (against Qt 5, most likely)
The std::optional<bool> was working fine for me with Qt 6.4.2, but
didn't compile in CI since for this type the following static assertion
failed:

    /opt/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h: In instantiation of ‘constexpr int qMetaTypeId() [with T = std::optional<bool>]’:
    /opt/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h:385:39:   required from ‘bool QVariant::canConvert() const [with T = std::optional<bool>]’
    /home/runner/work/tiled/tiled/src/tiled/automapper.cpp:182:9:   required from ‘bool Tiled::checkOption(const QString&, const QVariant&, QLatin1String, Type&) [with Type = std::optional<bool>]’
    /home/runner/work/tiled/tiled/src/tiled/automapper.cpp:258:90:   required from here
    /opt/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h:121:49: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system

Fixed by using a plain old separate bool member instead.