Qbs: Fixed build issue related to Info.plist file
For now, just moved the Info.plist file to the 'osx' section. I have not
checked yet whether it actually does what is expected there.

This is happening with more recent versions of Qbs:

error: Cannot install '.../tiled/src/tiled/Info.plist', because it doesn't start with the value of qbs.installSourceBase '...'.
(cherry picked from commit 368a88edb3487e59fd732370189b6c08727b63f8)