Fixed compile when using MSVC 2013
This compiler doesn't fully support C++11 and claims:

src\libtiled\properties.h(53) : error C2610: 'Tiled::Properties::Properties(Tiled::Properties &&)' : is not a special member function which can be defaulted
src\libtiled\properties.h(57) : error C2610: 'Tiled::Properties &Tiled::Properties::operator =(Tiled::Properties &&)' : is not a special member function which can be defaulted

I think these members aren't so important anyway since Qt does implicit
sharing.